// ... existing code ...
// Remove or comment out this line to avoid duplicate/conflicting AJAX handler registration
// add_action('wp_ajax_wcac_handle_upload_test_csv', ['Wcac_Admin_Ajax', 'handle_upload_test_csv_ajax']);
// ... existing code ... 